FROM i386/alpine:edge
#替换为国内源
#RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

ENV GLIB_VERSION=2.26-5
ENV GLIB_ARCH=i686

ADD ./ld.so.conf ./tmp/ld.so.conf
#设置glibc
RUN apk add --update --no-cache wget tar xz && \
    mkdir -p glibc-${GLIBC_VERSION} \
    /usr/glibc && \
    ln -s /bin/bash /usr/bin/bash && \
    wget http://archive.virtapi.org/packages/g/glibc/glibc-${GLIB_VERSION}-${GLIB_ARCH}.pkg.tar.xz -O glibc-${GLIB_VERSION}-${GLIB_ARCH}.pkg.tar.xz && \
    tar xf glibc-${GLIB_VERSION}-${GLIB_ARCH}.pkg.tar.xz -C glibc-${GLIBC_VERSION} && \
    mv tmp/ld.so.conf /etc/ld.so.conf && \
    cp -a glibc-${GLIBC_VERSION}/usr /usr/glibc/ && \
    glibc-${GLIBC_VERSION}/usr/bin/ldconfig /usr/glibc/usr /usr/glibc/usr/lib && \
    ln -s /usr/glibc/usr/lib/ld-linux.so.2 /lib/ld-linux.so.2  && \
    rm -Rf glibc-${GLIBC_VERSION} glibc-${GLIB_VERSION}-${GLIB_ARCH}.pkg.tar.xz && \ 
    apk del wget tar xz
#安装simsrv依赖库
RUN apk add --update --no-cache file lksctp-tools mariadb-client-libs libssl1.0 zlib musl
#建立动态链接
RUN ln -s /lib/libc.musl-x86.so.1 /usr/lib/libc.musl-x86.so.1 && \
    ln -s /lib/libz.so.1 /usr/lib/libz.so.1

RUN mkdir -p /var/log/

ADD dinstar/bin/* /dinstar/bin/
ADD dinstar/cfg/* /dinstar/cfg/
RUN chmod 777 -R /dinstar
WORKDIR /dinstar/bin/
CMD ["/bin/sh","-c","while true; do sleep 1; done"]
#CMD ["./simsrv"]
