#FROM vimalathithen/alpine-glibc-x86
FROM i386/alpine

RUN apk --no-cache add ca-certificates openssl && \
    wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub && \
    apk --no-cache -X http://apkproxy.heroku.com/sgerrand/alpine-pkg-glibc add glibc glibc-bin

#RUN apk update && apk add --no-cache glib-dev libc-dev lksctp-tools
RUN apk update && apk add --no-cache lksctp-tools-dev

RUN mkdir -p /var/log/

ADD dinstar/bin/* /dinstar/bin/
ADD dinstar/cfg/* /dinstar/cfg/
RUN chmod 777 -R /dinstar

RUN touch /var/log/simsrv.log
RUN chmod 777 /var/log/simsrv.log

WORKDIR /dinstar/bin/
CMD ["/bin/sh","-c","while true; do sleep 1; done"]
